author: ''

description: 'Detect trojan source attacks that employ unicode bidi attacks to inject malicious code'

name: 'anti-trojan-source'

branding:
  icon: 'shield'
  color: 'blue'

runs:
  using: 'docker'
  image: 'Dockerfile'
